name: ppa-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - langgraph>=0.0.10
    - langchain>=0.1.0
    - langchain-openai>=0.0.5
    - python-dotenv>=1.0.0
    - pydantic>=2.0.0
    - typing-extensions>=4.5.0 